# Site settings
title: gli. desu. yo. 
email: ore.wa.glidesu@gmail.com 
description: "gli. desu. yoroshiku."
baseurl: ""
url: "http://glidesu.github.io"

# Build settings
markdown: kramdown
permalink: pretty
