# Site settings
username: chamoji
title: the joy of learning 
email: westley.mojica@gmail.com 
baseurl: "http://chamoji.github.io"
url: "http://chamoji.github.io"

# Build settings
markdown: kramdown
permalink: pretty
