# Site settings
username: chamoji
twitter: glidesu
title: I am chamoji
email: westley.mojica@gmail.com 
description: "the joy of learning"
baseurl: ""
url: "http://chamoji.github.io"

# Build settings
markdown: kramdown
permalink: pretty
